version: '3.7'

services:
  pad-b-gateway: 
    build: ../gateway/   
    depends_on:
      - pad-b-registry
    ports:
        - '8080:8080'
      
  pad-b-registry: 
     build: ../registry/
     ports:
         - '8761:8761'

  pad-b-users:
    build:  ../user/
    depends_on:
      - pad-b-registry
      - pad-b-gateway
    ports:
        - '8084:8084'
    environment:
          - SERVER_URL=pad-b-users
          - EUREKA_URL=pad-b-registry
         
    