version: '3.7'

services:
  pad-b-gateway: 
    build: ../gateway/   
    depends_on:
      - pad-b-registry
      - pad-b-config
    ports:
        - '8080:8080'
    env_file: 
        - ./gateway/local.env
    restart: on-failure
    links:
      - pad-b-registry
      - pad-b-config
      
  pad-b-registry: 
     build: ../registry/
     ports:
         - '8761:8761'
     env_file:
      - ./registry/local.env
     links: 
      - elasticsearch
      - kibana
      - logstash
      - filebeat 

  pad-b-users:
    build:  ../user/
    depends_on:
      - pad-b-registry
      - pad-b-gateway
      - pad-b-users-database
    ports:
        - '8084:8084'
    env_file: 
        - ./users/local.env
         
  pad-b-users-database:
      image: postgres
      restart: always
      ports:
          - '5432:5432'
      environment: 
          POSTGRES_DB: users 
          POSTGRES_USER: users 
          POSTGRES_PASSWORD: secure123
          
  pad-b-auth:
     build: ../auth/
     depends_on:
       - pad-b-registry
       - pad-b-auth-database
       - pad-b-config
     ports:
         - '8082:8082'
     env_file: 
        - ./auth/local.env
     restart: on-failure
        
  pad-b-auth-database:
     image: mongo:latest
     environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
          - MONGO_INITDB_DATABASE=admin
     ports:
            - 27017:27017

  pad-b-config: 
     build: ../config/
     depends_on:
       - pad-b-registry
       - pad-b-config-database
     ports:
         - '8086:8086'
     env_file: 
        - ./config/local.env
     links:
       - pad-b-registry
       - pad-b-config-database
      
        
  pad-b-config-database:
     image: mongo:latest
     command: mongod --port 27018
     environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
          - MONGO_INITDB_DATABASE=admin
     ports:
            - 27018:27018

            
  pad-b-audit: 
     build: ../audit/Audit/.
     restart: always
     depends_on:
       - pad-b-audit-database
       - pad-b-registry
       - pad-b-gateway
       - pad-b-config
     ports:
         - '8087:8087'
     env_file: 
        - ./audit/local.env
     links:
       - pad-b-audit-database
       - pad-b-registry
       - pad-b-gateway
       - pad-b-config 
        
  pad-b-audit-database:
     image: couchdb:latest
     restart: always
     environment:
        - COUCHDB_PASSWORD=123456
        - COUCHDB_USER=admin
     ports:
        - 5986:5986       

  pad-b-tracing: 
     restart: on-failure
     build: ../tracing/
     depends_on:
       - pad-b-registry
     ports:
         - '8090:8090'
     env_file: 
        - ./tracing/local.env
                 
  pad-b-rabbit:
     image: rabbitmq:3-management-alpine
     hostname: rabbit
     restart: on-failure
     ports:
       - 15672:15672
       - 5672:5672
     volumes:
        - rabbitmq:/var/lib/rabbitmq:rw
        - ./rabbit/definitions.json:/opt/definitions.json:ro
        - ./rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
       
  pad-b-notification:
     build: ../notification/.
     ports:
        - '8089:8089'
     env_file:
       - ./notification/local.env
     restart: on-failure

  filebeat:
     hostname: filebeat
     build:
      context: ../logging/filebeat
     volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
     links:
       - logstash
       - elasticsearch
       - kibana

  kibana:
     image: docker.elastic.co/kibana/kibana:6.5.3
     environment:
      - "LOGGING_QUIET=true"
     links:
      - elasticsearch
     ports:
      - 5601:5601

  logstash: 
     hostname: logstash
     build:
      context: ../logging/logstash
     ports:
      - 5044:5044
     environment:
      LOG_LEVEL: error
     links:
      - elasticsearch

  elasticsearch:
     hostname: elasticsearch
     build:
      context: ../logging/elasticsearch
     environment:
      - cluster.name=pad-b-elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
     ulimits:
      memlock:
        soft: -1
        hard: -1
     ports:
      - 9200:9200
     
volumes:
    rabbitmq:

  