version: '3.7'

services:
  pad-b-gateway: 
    build: ../gateway/   
    depends_on:
      - pad-b-registry
    ports:
        - '8080:8080'
    env_file: 
        - ./gateway/local.env
      
  pad-b-registry: 
     build: ../registry/
     ports:
         - '8761:8761'
     env_file:
      - ./registry/local.env

  pad-b-users:
    build:  ../user/
    depends_on:
      - pad-b-registry
      - pad-b-gateway
      - pad-b-users-database
    ports:
        - '8084:8084'
    env_file: 
        - ./users/local.env
         

  pad-b-users-database:
      image: postgres
      restart: always
      ports:
          - '5432:5432'
      environment: 
          POSTGRES_DB: users 
          POSTGRES_USER: users 
          POSTGRES_PASSWORD: secure123
          
  pad-b-auth:
     build: ../auth/
     depends_on:
       - pad-b-registry
       - pad-b-auth-database
     ports:
         - '8082:8082'
     env_file: 
        - ./auth/local.env
        
  pad-b-auth-database:
     image: mongo:latest
     environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
          - MONGO_INITDB_DATABASE=admin
     ports:
            - 27017:27017

  pad-b-config: 
     build: ../config/
     depends_on:
       - pad-b-registry
       - pad-b-config-database
     ports:
         - '8086:8086'
     env_file: 
        - ./config/local.env
        
  pad-b-config-database:
     image: mongo:latest
     command: mongod --port 27018
     environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
          - MONGO_INITDB_DATABASE=admin
     ports:
            - 27018:27018
         

    