version: '3.7'

services:
  pad-b-gateway: 
    build: ../gateway/   
    depends_on:
      - pad-b-registry
    ports:
        - '8080:8080'
      
  pad-b-registry: 
     build: ../registry/
     ports:
         - '8761:8761'
         
         
  pad-b-auth:
     build: ../auth/
     depends_on:
       - pad-b-registry
       - pad-b-mongodb-auth
     ports:
         - '8082:8082'
         
  pad-b-mongodb-auth:
     image: mongo:latest
     environment:
          - MONGODB_USER="root" 
          - MONGODB_PASS="root"
     ports:
            - 27017:27017 
         
    